name = "MyCompatPkg"
uuid = "3ed6c5b6-575b-460a-8104-4a88f384643e"
authors = [""]
version = "1.1.0"

[deps]
MyPublicPkg = "a6e8d7c3-1fe2-45dc-81fa-a6c45a4fa21b"

[compat]
MyPublicPkg = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
