name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/cache@v1
      - uses: MyExampleOrg/.CI/setup-registry@master
        with:
          token: ${{ secrets.token }}
          registers: MyExampleOrg/MyPublicRegistry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
      - run: |
          julia -e '
          using Pkg
          Pkg.add("CompatHelper")
          using CompatHelper
          CompatHelper.main(use_existing_registries = true)
          '
