name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Configure CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: |
          julia -e '
          using Pkg
          Pkg.add("CompatHelper")
          using CompatHelper
          CompatHelper.main(; registries = [
            Pkg.RegistrySpec(
                url = "https://github.com/JuliaRegistries/General.git",
            ),
            Pkg.RegistrySpec(
                url = "https://github.com/MyExampleOrg/MyPublicRegistry.git",
            ),
          ])
          '
